apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: metallb
  version: v0.15.2
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  namespace: metallb-system
  valuesFile: values.yaml
