apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cert-manager
  version: v0.15.2
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml
  includeCRDs: true