apiVersion: v1
data:
  slack_api_url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA5Rzg4OTU2VUUvQjA5TUcwSkVOTlAvbFRnYVczbFpXWElWWWxiYkJ2OHJydEw2
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-webhook
  namespace: monitoring
