global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
- target_matchers:
  - alertname = InfoInhibitor
receivers:
- name: "slack"
  slack_configs:
    - api_url: 'https://hooks.slack.com/services/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'
      channel: '#alerts'
      send_resolved: true
      title: |-
        [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} - {{ .CommonLabels.severity }}
      text: |-
        {{ range .Alerts }}
        *Summary:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Starts At:* {{ .StartsAt }}
        *Ends At:* {{ .EndsAt }}
        *Namespace:* {{ .Labels.namespace }}
        *Pod:* {{ .Labels.pod }}
        {{ end }}
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: "slack"
  repeat_interval: 12h
  routes:
    - matchers:
        - severity = critical|warning|info
      receiver: "slack"
templates:
- /etc/alertmanager/config/*.tmpl
