apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kube-prometheus-stack
  version: v0.85.0
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: prometheus
  valuesFile: values.yaml

