apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-rules.yaml

helmCharts:
- name: kube-prometheus-stack
  version: 77.10.0
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: prometheus
  valuesFile: values.yaml

secretGenerator:
- name: alertmanager-config
  files:
  - alertmanager.yaml=alertmanager-config.yaml
  type: Opaque
generatorOptions:
  disableNameSuffixHash: true


