apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: backstage
  version: 2.8.2
  repo: oci://ghcr.io/backstage/charts
  releaseName: backstage
  namespace: backstage
  valuesFile: values.yaml
  includeCRDs: true
